language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_TARGET=android-16  
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=8 # minutes

  
android:
  components:
  - android-23
  - build-tools-23.0.2
  - platform-tools
  - tools
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
 
script:
    - ./gradlew clean build jacocoTestReport assembleAndroidTest
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -s "1080x1920"
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
    - ./gradlew connectedCheck
    
  
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
    