#based on https://docs.travis-ci.com/user/languages/android
language: android
jdk: oraclejdk7

env:
  global:
  - ANDROID_TARGET=android-23  
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=8 # minutes

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
android:
  components:
  - android-23
  - build-tools-23.0.1
  - platform-tools
  - tools
  - extra-android-m2repository
  - extra-google-m2repository
  # emulator (if we want to test a little)
  - sys-img-armeabi-v7a-android-21
 
script:
    #fix for android bug https://code.google.com/p/android/issues/detail?id=189764&q=label%3APriority-Medium&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
    ./gradlew clean assemble lint
    ./gradlew assembleDebug
    ./gradlew assembleDebugAndroidTest
    adb install app/build/outputs/apk/app-debug.apk
    adb install app/build/outputs/apk/app-debug-androidTest-unaligned.apk
    adb shell am instrument -w com.google.samples.apps.topeka.test/android.support.test.runner.AndroidJUnitRunner
  
  